config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  
  resources :events do
    resources :attendees, only: [:create, :destroy]
  end

  resources :invitations, only: [:index, :show, :create, :update, :destroy]

  root to: "events#index"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :attended_events, class_name: "Event", join_table: "attended_events_attendees"
  has_many :hosted_events, class_name: "Event", foreign_key: "host_id", inverse_of: :host, dependent: :destroy
  
  has_many :sent_invitations, class_name: "Invitation", foreign_key: "sender_id", inverse_of: :sender, dependent: :destroy
  has_many :received_invitations, class_name: "Invitation", foreign_key: "invitee_id", inverse_of: :invitee, dependent: :destroy
  has_many :invited_events, through: :received_invitations, source: :event
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<section class="section">
<div class="columns">
    <div class="column is-half is-offset-one-quarter">
    <h2 class="title is-3">User Profile</h2>
        <div class="box">
            <h3 class="title is-4"><%= @user.name %></h3>
            <h4 class="subtitle">Joined <%= time_ago_in_words(@user.created_at) %> ago</h4>
            <div class="container">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce lacinia felis id metus ultricies suscipit. Nulla nec malesuada tortor. Pellentesque posuere elit et scelerisque pulvinar. In posuere nulla in nisl egestas posuere. Nulla feugiat at neque at pretium. Nulla tempus nibh vel neque viverra pretium. Donec odio leo, iaculis id nunc non, bibendum feugiat ipsum. Maecenas nec lobortis arcu. Curabitur bibendum vestibulum ligula, hendrerit laoreet lorem rutrum ac. Suspendisse iaculis purus eu luctus venenatis. Nullam ac nunc quis nibh tristique laoreet. Aliquam molestie fringilla vehicula. Integer bibendum tincidunt tempus. Aenean vitae suscipit nulla, in iaculis nulla. Phasellus a ipsum a quam porttitor vestibulum vitae eget nunc. Cras ut feugiat lorem.</p>
            </div>
        </div>
        
        <h2 class="title is-3"><%= @user.name %>'s Events</h2>

        <div class="tabs is-large is-boxed">
            <ul>
                <li id="attended_events_tab" class="tab is-active"><a>Attending</a></li>
                <li id="hosted_events_tab" class="tab"><a>Hosting</a></li>
            </ul>
        </div>

        <div id="attended_events_container" class="container">
            <% unless @user.attended_events.empty? %>
                <% @user.attended_events.each do |event| %>
                    <div class="box">
                            <%= link_to event_path(event) do %>
                                <h3 class="title is-4"><%= event.title %></h3>
                            <% end %>
                            <h4 class="subtitle"><%= event.start_date %></h4>
                            <div class="content">
                                <%= event.body%>
                            </div>
                        
                    </div>
                <% end %>
            <% else %>
                <div class="content">
                    This user is not attending any events at the moment.
                </div>
            <% end %>
        </div>

        <div id="hosted_events_container" class="container is-hidden">
            <% unless @user.hosted_events.empty? %>
                    <% @user.hosted_events.each do |event| %>
                        <div class="box">
                                <%= link_to event_path(event) do %>
                                    <h3 class="title is-4"><%= event.title %></h3>
                                <% end %>
                                <h4 class="subtitle"><%= event.start_date %></h4>
                                <div class="content">
                                    <%= event.body%>
                                </div>
                            
                        </div>
                    <% end %>
                <% else %>
                    <div class="content">
                        This user is not hosting any events at the moment.
                    </div>
                <% end %>
        </div>
        
    </div>
    <% if user_signed_in? && current_user != @user %>
        <div class="column is-one-quarter">
            <div class="box">
                <h3 class="title is-4">Invite to an event</h3>
                <%= render 'invitations/invite_user_form', invitee: @user, invitation: Invitation.new %>
            </div>
        </div>
    <% end %>
</div>
</section>