config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  
  resources :events do
    resources :attendees, only: [:create, :destroy]
  end

  resources :invitations, only: [:index, :show, :create, :update, :destroy]

  root to: "events#index"

end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :host, class_name: "User"
    has_many :invitations, dependent: :destroy
    has_many :invitees, through: :invitations
    has_and_belongs_to_many :attendees, class_name: "User", join_table: "attended_events_attendees"

    scope :upcoming, ->{ where("events.start_date >= ?", DateTime.current) }
    scope :ongoing, ->{ where("events.start_date < :current_datetime AND events.end_date > :current_datetime", current_datetime: DateTime.current)}
    scope :past, ->{ where("events.end_date < ?", DateTime.current) }

    VALID_OPENNESS_SETTINGS = ['invite_only', 'public']

    validates :openness, inclusion: {in: VALID_OPENNESS_SETTINGS }

    def pretty_start_date
        self.start_date.strftime('%B %-d, %Y')
    end

    def start_time
        self.start_date.localtime.strftime('%k:%M')
    end

    def upcoming?
        start_date >= DateTime.current
    end

    def past?
        end_date < DateTime.current
    end

    def ongoing?
        start_date < DateTime.current && end_date > DateTime.current
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :calculate_date, only: [:create, :update]

    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = current_user.hosted_events.build
    end

    def create
        @event = current_user.hosted_events.build(event_params)

        if @event.save
            flash[:notice] = "Successfully created event!"
            redirect_to event_path(@event)
        else
            flash.now[:alert] = "There was a problem creating your event."
            render "new"
        end
    end

    def edit
        begin
            @event = current_user.hosted_events.find(params[:id])
        rescue
            if Event.find_by(id: params[:id])
                flash[:alert] = "You don't have permission to edit that event."
            else
                flash[:alert] = "That event doesn't exist."
            end
            redirect_to root_path
        end
    end

    def update
        begin
            @event = current_user.hosted_events.find(params[:id])
        rescue
            if Event.find_by(id: params[:id])
                flash[:alert] = "You don't have permission to edit that event."
            else
                flash[:alert] = "That event doesn't exist."
            end
            redirect_to root_path
        end

        if @event.update(event_params)
            flash[:notice] = "Successfully updated event."
            redirect_to event_path(@event)
        else
            flash[:alert] = "There was a problem updating your event."
            render "edit"
        end
    end

    def destroy
        begin
            @event = current_user.hosted_events.find(params[:id])
        rescue
            if Event.find_by(id: params[:id])
                flash[:alert] = "You don't have permission to delete that event."
            else
                flash[:alert] = "That event doesn't exist."
            end
            redirect_to root_path
        end

        @event.destroy
        redirect_to root_path
    end

    private
    def event_params
        params.require(:event).permit(:title, :body, :start_date, :end_date, :openness)
    end

    def calculate_date
        tz = ActiveSupport::TimeZone.new(params.fetch("time_zone", "Tokyo")).formatted_offset
        end_date = params[:event][:start_date] > params[:event][:end_date] ? params[:event][:start_date] : params[:event][:end_date]
        params[:event][:start_date] = "#{params[:event][:start_date]}T#{params.fetch("start_time", "00:00:00")}#{tz}"
        params[:event][:end_date] = "#{end_date}T#{params.fetch("end_time", "00:00:00")}#{tz}"
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_snippet.html.erb
<div class="box">
    <%= link_to event_path(event) do %>
        <h3 class="title is-4"><%= event.title %></h3>
    <% end %>
    <h4 class="subtitle">
        <% if event.upcoming? %>
            Starts on <%= event.start_date.localtime.strftime('%B %-d, %Y at %k:%M') %>
        <% elsif event.ongoing? %>
            Started on <%= event.start_date.localtime.strftime('%B %-d, %Y at %k:%M') %>
        <% else %>
            Ended on <%= event.end_date.localtime.strftime('%B %-d, %Y at %k:%M') %>
        <% end %>
        &nbsp;(GMT <%= event.start_date.localtime.formatted_offset %>)
    </h4>
    <div class="content">
        <%= event.body%>
    </div>     
</div>

app/views/events/_form.html.erb
<%= form_with model: event do |f| %>
<div class="field">
    <div class="control">
        <%= f.label :title, class: "label" %>
        <%= f.text_field :title, class: "input" %>
    </div>
</div>

<div class="field">
    <div class="control">
        <%= f.label :body, class: "label" %>
        <%= f.text_area :body, class: "textarea", rows: "10" %>
    </div>
</div>
<fieldset>
    <legend class="title is-4">Date and time</legend>
    <div class="level">
        <div class="level-left">
            <div class="level-item">
                <div class="field">
                    <div class="control">
                        <%= f.label :start_date, class: "label" %>
                        <%= f.date_field :start_date, class: "input" %>
                    </div>
                </div>
            </div>

            <div class="level-item">
                <div class="field">
                    <div class="control">
                        <label for="start_time" class="label">Start Time</label>
                        <input type="time" id="start_time" name="start_time" class="input" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="level">
        <div class="level-left">
            <div class="level-item">
                <div class="field">
                    <div class="control">
                        <%= f.label :end_date, class: "label" %>
                        <%= f.date_field :end_date, class: "input" %>
                    </div>
                </div>
            </div>
            <div class="level-item">
                <div class="field">
                    <div class="control">
                        <label for="end_time" class="label">End Time</label>
                        <input type="time" id="end_time" name="end_time" class="input" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="level">
        <div class="level-left">
            <div class="level-item">
                <div class="field">
                    <div class="control">
                        <label for="time_zone" class="label">Timezone</label>
                        <div class="select">
                            <select name="time_zone" id="time_zone">
                                <%= time_zone_options_for_select "Tokyo" %>
                            </select>
                        </div>    
                    </div>
                </div>
            </div>
        </div>
    </div>
</fieldset>
<br />
    <div class="field">
        <div class="control">
            <%= f.label :openness, "Event settings", class: "label" %>
            <div class="select">
                <%= f.select :openness, Event::VALID_OPENNESS_SETTINGS.map { |e| [e.gsub("_", " ").capitalize, e] } %>
            </div>
        </div>
    </div>

<div class="field">
    <div class="control">
        <%= f.submit class: "button is-primary" %>
    </div>
</div>
<% end %>

app/views/events/edit.html.erb
<section class="section">
    <div class="columns">
        <div class="column is-half is-offset-one-quarter">
            <div class="box">
                <h2 class="title is-3">Edit event</h2>
                <%= render 'form', event: @event %>
            </div>
        </div>
    </div>
</section>

app/views/events/index.html.erb
<section class="section">
    <div class="columns">
        <div class="column is-two-thirds is-offset-2">
            <div class="tabs is-large is-boxed">
                <ul>
                    <li id="upcoming_events_tab" class="tab is-active"><a>Upcoming</a></li>
                    <li id="ongoing_events_tab" class="tab"><a>Ongoing</a></li>
                    <li id="past_events_tab" class="tab"><a>Past</a></li>
                </ul>
            </div>

            <div id="upcoming_events_container" class="container">
                <h2 class="title is-3">Upcoming Events</h2>
                <% unless @events.upcoming.empty? %>
                    <% @events.upcoming.each do |event| %>
                        <%= render 'events/event_snippet', event: event %> 
                    <% end %>
                <% else %>
                <div class="content">
                    There aren't any upcoming events at the moment.
                </div>
                <% end %>
            </div>
            
            <div id="ongoing_events_container" class="container is-hidden">
                <h2 class="title is-3">Ongoing Events</h2>
                <% unless @events.ongoing.empty? %>
                    <% @events.ongoing.each do |event| %>
                        <%= render 'events/event_snippet', event: event %> 
                    <% end %>
                <% else %>
                    <div class="content">
                        There aren't any ongoing events at the moment.
                    </div>
                <% end %>
            </div>
            
            <div class="container is-hidden" id="past_events_container">
                <h2 class="title is-3">Past Events</h2>
                <% unless @events.past.empty? %>
                    <% @events.past.each do |event| %>
                        <%= render 'events/event_snippet', event: event %>
                    <% end %>
                <% else %>
                    <div class="content">
                        There aren't any past events at the moment.
                    </div>
                <% end %>
            </div>

            
            
        </div>
    </div>
</section>

app/views/events/new.html.erb
<section class="section">
<div class="columns">
<div class="column is-half is-offset-one-quarter">
<div class="box">
<h2 class="title is-3">Create new event</h2>

<%= form_with model: @event do |f| %>
<div class="field">
    <div class="control">
        <%= f.label :title, class: "label" %>
        <%= f.text_field :title, class: "input" %>
    </div>
</div>

<div class="field">
    <div class="control">
        <%= f.label :body, class: "label" %>
        <%= f.text_area :body, class: "input" %>
    </div>
</div>


<div class="level">

<div class="level-item">
<div class="field">
    <div class="control">
        <%= f.label :start_date, class: "label" %>
        <%= f.datetime_local_field :start_date, class: "input" %>
    </div>
</div>
</div>

<div class="level-item">
<div class="field">
    <div class="control">
        <%= f.label :end_date, class: "label" %>
        <%= f.datetime_local_field :end_date, class: "input" %>
    </div>
</div>
</div>


</div>


<div class="field">
    <div class="control">
        <%= f.submit "Create Event", class: "button is-primary" %>
    </div>
</div>
<% end %>

</div>
</div>
</div>
</section>

app/views/events/show.html.erb
<section class="section">
<div class="columns">
<div class="column is-half is-offset-one-quarter">
    <div class="box">
        <h2 class="title is-3"><%= @event.title %></h2>
        <h3 class="subtitle">
            <% if @event.upcoming? %>
                Starts on <%= @event.start_date.localtime.strftime('%B %-d, %Y at %k:%M') %>
            <% elsif @event.ongoing? %>
                Started on <%= @event.start_date.localtime.strftime('%B %-d, %Y at %k:%M') %>
            <% else %>
                Ended on <%= @event.end_date.localtime.strftime('%B %-d, %Y at %k:%M') %>
            <% end %>
        </h3>
        <div class="content">
            <strong>Date</strong>: <%= @event.pretty_start_date %>
            <% if @event.end_date && @event.end_date.yday != @event.start_date.yday %>
            &nbsp;to <%= @event.end_date.localtime.strftime('%B %-d') %>
            <% end %><br />
            <strong>Time</strong>: <%= @event.start_time %>
            <% if @event.end_date && @event.end_date.localtime.strftime('%k:%M') != @event.start_time %>
            &nbsp;to <%= @event.end_date.localtime.strftime('%k:%M') %>
            <% end %>
            &nbsp;(GMT <%= @event.start_date.localtime.formatted_offset%>)
            <br />
            <strong>Openness</strong>: <%= @event.openness.gsub("_", " ").capitalize %>
            <p><%= @event.body %></p>
        </div>
        <div class="content">
            <small>Created by <%= link_to @event.host.email, user_path(@event.host) %></small>
        </div>
        <div class="level">
            <div class="level-left">
                <div class="level-item">
                    <% if user_signed_in? && current_user.attended_events.include?(@event) %>
                        <%= link_to "Skip", event_attendee_path(@event, current_user), 
                            method: :delete, class: "button is-danger is-light"%>
                    <% else %>
                        <%= link_to event_attendees_path(@event), method: :post do %>
                            <button class="button is-primary" <%= "disabled" if @event.past? %>>Attend</button>
                        <% end %>
                    <% end %>
                </div>
            </div>
            
            <% if user_signed_in? && current_user == @event.host %>
            <div class="level-right">
                <div class="level-item">
                    <%= link_to edit_event_path(@event), class: "button is-warning" do %>
                        <span class="icon"><i class="fas fa-edit"></i></span>
                    <% end %>
                </div>
                <div class="level-item">
                    <%= link_to event_path(@event), method: :delete, data: { confirm: "Are you sure you want to delete this event?"},
                        class: "button is-danger" do %>
                        <span class="icon"><i class="fas fa-trash"></i></span>
                    <% end %>
                </div>
            </div>
            <% end %>
            
        </div>
    </div>
</div>
<div class="column is-one-quarter">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="title is-3">Attendees</h3>
        </div>
        <div class="content">
            <% if @event.attendees.empty? %>
                No attendees yet
            <% else %>
                <ul>
                <% @event.attendees.each do |attendee| %>
                    <li>
                    <%= link_to attendee.name, user_path(attendee) %>
                    </li>
                <% end %>
                </ul>
            <% end %>
        </div>
    </div>

    <% if user_signed_in? && current_user == @event.host %>
    <div class="box">
     <h3 class="title is-4">Invite users</h3>
     <%= render 'invitations/invite_form', invitation: Invitation.new, event: @event %>
    </div>
    <% end %>
</div>

</div>
</section>