config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  
  resources :events do
    resources :attendees, only: [:create, :destroy]
  end

  resources :invitations, only: [:index, :show, :create, :update, :destroy]

  root to: "events#index"

end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :invitee, class_name: "User"
    belongs_to :event

    VALID_STATUSES = ['pending', 'accepted', 'rejected']

    validates :status, inclusion: { in: VALID_STATUSES }
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
    before_action :authenticate_user!

    def index
        @sent_invitations = current_user.sent_invitations.all
        @received_invitations = current_user.received_invitations.all
    end

    def create
        @event = Event.find_by(id: invitation_params[:event_id])
        if @event.host == current_user
            @invitee = User.find_by(invitation_params[:invitee])
            @invitation = current_user.sent_invitations.build(event_id: @event.id,
                                                              invitee_id: @invitee&.id,
                                                              body: invitation_params[:body],
                                                              status: 'pending')

            if @invitation.save
                flash[:notice] = "Successfully sent invitation!"
                redirect_to event_path(@event)
                return
            end
        end
        flash.now[:alert] = "Unable to send invitation"
        render 'events/show', locals: { event: @event }
    end

    def update
        @invitation = current_user.received_invitations.find_by(id: response_params[:id])

        if @invitation&.update(response_params)
            @invitation.event << current_user if @invitation.status == 'accepted'
            flash[:notice] = "Successfully responded to invitation!"
        else
            flash[:alert] = "Unable to respond to invitation."
        end
        redirect_to user_path(current_user)
    end

    def destroy
        @invitation = current_user.sent_invitations.find_by(id: params[:id])

        if @invitation&.destroy
            flash[:notice] = "Successfully deleted invitation"
        else
            flash[:alert] = "Unable to delete invitation."
        end

        redirect_to invitations_path
    end

    private
    def invitation_params
        params.require(:invitation).permit(:event_id, :body, :status, invitee: {} )
    end

    def response_params
        params.require(:invitation).permit(:id, :status)
    end

end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_invite_form.html.erb
<%= form_with model: invitation do |f| %>
    <%= f.hidden_field :event_id, value: event.id %>

    <div class="field">
        <div class="control">
            <%= f.label "invitee", "Username", class: "label" %>
            <%= f.text_field "invitee", class: "input" %>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.label :body, "Message", class: "label" %>
            <%= f.text_area :body, class: "textarea", rows: "5" %>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.submit "Invite", class: "button is-info" %>
        </div>
    </div>
<% end %>

app/views/invitations/_invite_user_form.html.erb
<%= form_with model: invitation do |f| %>

    <%= f.hidden_field "invitee[id]", value: invitee.id %>

    <div class="field">
        <div class="control">
        <%= f.label :event_id, "Invite to", class: "label" %>
        <div class="select">
            <%= f.select :event_id, current_user.hosted_events.map { |e| [e.title, e.id] } %>
        </div> 
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.label :body, "Message", class: "label" %>
            <%= f.text_area :body, class: "textarea", rows: "5" %>
        </div>
    </div>

    <div class="field">
        <div class="control">
            <%= f.submit "Invite", class: "button is-info" %>
        </div>
    </div>
<% end %>

app/views/invitations/index.html.erb
<section class="section">
    <div class="columns">
        <div class="column is-two-thirds is-offset-2">

            <div class="tabs is-centered is-large is-boxed">
                <ul>
                    <li id="sent_invitations_tab" class="tab is-active"><a>Sent</a></li>
                    <li id="received_invitations_tab" class="tab"><a>Received</a></li>
                </ul>
            </div>

            <div id="sent_invitations_container" class="container">
                <% @sent_invitations.each do |sent_inv| %>
                    <div class="box">
                        <h3 class="title is-4">You invited <%= link_to sent_inv.invitee.name, user_path(sent_inv.invitee) %> to <%= link_to sent_inv.event.title, event_path(sent_inv.event) %></h3>
                        <h4 class="subtitle"><strong>Sent</strong>: <%= sent_inv.created_at %></h4>
                        <strong>You wrote:</strong>
                        <p>
                            <%= sent_inv.body %>
                        </p>
                        <% if sent_inv.status == "accepted" %>
                            <%= sent_inv.invitee.name %> accepted your invitation at <%= sent_inv.updated_at %>.
                        <% elsif sent_inv.status == "rejected" %>
                            <%= sent_inv.invitee.name %> denied your invitation <%= sent_inv.updated_at %>.
                        <% else %>
                            <%= sent_inv.invitee.name %> has not responded yet.
                        <% end %>

                        <div class="level">
                                <div class="level-item level-right">
                                    <%= link_to invitation_path(sent_inv), method: :delete, class: "button is-danger"  do %>
                                        <span class="is-icon"><i class="fas fa-trash"></i></span>
                                    <% end %>
                                </div>
                        </div>
                    
                    
                    </div>
                <% end %>

                <% if @sent_invitations.empty? %>
                        You have no sent invitations at this time.
                    <% end %>
            
            </div>
            <br />
            <div id="received_invitations_container" class="container is-hidden">
                    <% @received_invitations.each do |received_inv| %>
                        <div class="box">
                            <h3 class="title is-4">You were invited to <%= link_to received_inv.event.title, event_path(received_inv.event) %> by <%= link_to received_inv.sender.name, user_path(received_inv.sender) %></h3>
                            <h4 class="subtitle"><strong>Received</strong>: <%= received_inv.created_at %></h4>
                            <strong>They wrote:</strong>
                            <p>
                                <%= received_inv.body %>
                            </p>
                            <% if received_inv.status == "pending" %>
                                You haven't responded yet. Would you like to respond?

                                <%= form_with model: received_inv do |f| %>
                                    <%= f.hidden_field :id, value: received_inv.id %>
                                    <div class="field">
                                        <div class="control">
                                            <%= f.label :status, "Response:" %>
                                            <%= f.select :status, [["Accept", "accepted"], ["Decline", "rejected"]]%>
                                        </div>
                                    </div>
                                    <%= f.submit "Respond" %>
                                <% end %>
                            <% else %>
                                You <%= received_inv.status == "accepted" ? "accepted" : "declined" %> this invitation on <%= received_inv.updated_at %>
                            <% end %>
                        </div>
                    <% end %>
                    
                    <% if @received_invitations.empty? %>
                            You have not received any invitations at this time.
                    <% end %>
            </div>
        </div>
    </div>
</div>
</section>