config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  
  resources :events do
    resources :attendees, only: [:create, :destroy]
  end

  resources :invitations, only: [:index, :show, :create, :update, :destroy]

  root to: "events#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/bcdbdb9739.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if flash[:alert] %>
    <div class="notification is-danger global-notification"><%= flash[:alert] %></div>
  <% elsif flash[:notice] %>
    <div class="notification is-success global-notification"><%= flash[:notice] %></div>
  <% end %>

  <nav class="navbar">
  <div class="navbar-brand">
  <%= link_to root_path do %>
  <h1 class="title is-3">Private Events</h1>
  <% end %>

  <a role="button" class="navbar-burger" aria-label="main" aria-expanded="false">
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
  </a>
  </div>

  <div class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <%= link_to "Create Event", new_event_path, class: "button is-info"%>
      </div>
      
      <% if user_signed_in? %>
        <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= current_user.name %>
        </a>

        <div class="navbar-dropdown">
          <%= link_to "Profile", user_path(current_user), class: "navbar-item" %>
          <%= link_to "Invitations", invitations_path, class: "navbar-item" %> 
          <hr class="navbar-divider">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-item" %>
        </div>
      <% else %>
        <div class="navbar-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "button is-primary is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "Sign in", new_user_session_path, class: "button is-info is-light" %>
        </div>
      <% end %>
      
    </div>
  </div>
  </nav>

  


    <%= yield %>
  </body>
</html>